interface ProductFilter {
	[key: string]: {
		material?: { value: string; label: string }[];
		color?: { value: string; label: string }[];
		shape?: { value: string; label: string }[];
		style?: { value: string; label: string }[];
		finish?: { value: string; label: string }[];
		size?: { value: string; label: string }[];
		texture?: { value: string; label: string }[];
		backing?: { value: string; label: string }[];
		collection?: { value: string; label: string }[];
		Installation_Method?: { value: string; label: string }[];
		brand?: { value: string; label: string }[];
		pattern?: { value: string; label: string }[];
		faucets?: { value: string; label: string }[];
		Number_Of_Shelves?: { value: string; label: string }[];
		Faucet_Finish?: { value: string; label: string }[];
		Sink_Material?: { value: string; label: string }[];
		Number_Of_Basins?: { value: string; label: string }[];
		types?: { value: string; label: string }[];
	};
}

export const productFilter: ProductFilter = {
	tiles: {
		material: [
			{ value: "porcelain", label: "Porcelain" },
			{ value: "ceramic", label: "Ceramic" },
			{ value: "marble", label: "Marble" },
			{ value: "glass", label: "Glass" },
		],
		color: [
			{ value: "whites", label: "Whites" },
			{ value: "greys", label: "Greys" },
			{ value: "browns", label: "Browns" },
			{ value: "neutrals", label: "Neutrals" },
			{ value: "blacks", label: "Blacks" },
			{ value: "grays", label: "Grays" },
			{ value: "blues", label: "Blues" },
			{ value: "multi", label: "Multi" },
			{ value: "greens", label: "Greens" },
			{ value: "silver-tones", label: "Silver Tones" },
			{ value: "reds", label: "Reds" },
			{ value: "gold-tones", label: "Gold Tones" },
			{ value: "creams", label: "Creams" },
			{ value: "light-wood-finishes", label: "Light Wood Finishes" },
			{ value: "bronze-tones", label: "Bronze Tones" },
			{ value: "stainless-steel", label: "Stainless Steel" },
			{ value: "copper-tones", label: "Copper Tones" },
			{ value: "orange", label: "Oranges" },
			{ value: "purple", label: "Purples" },
			{ value: "yellow", label: "Yellows" },
		],
		shape: [
			{ value: "rectangular", label: "Rectangle" },
			{ value: "square", label: "Square" },
			{ value: "hexagon", label: "Hexagon" },
			{ value: "specialty", label: "Specialty" },
			{ value: "circle", label: "Circle" },
			{ value: "parallelogram", label: "Parallelogram" },
			{ value: "diamond", label: "Diamond" },
			{ value: "octagon", label: "Octagon" },
			{ value: "triangle", label: "Triangle" },
			{ value: "trapezoid", label: "Trapezoid" },
			{ value: "oval", label: "Oval" },
		],
		finish: [
			{ value: "brushed", label: "Brushed" },
			{ value: "matte", label: "Matte" },
			{ value: "polished", label: "Polished" },
		],
	},
	carpets: {
		color: [
			{ value: "beiges", label: "Beiges" },
			{ value: "blues", label: "Blues" },
			{ value: "browns", label: "Browns" },
			{ value: "golds", label: "Golds" },
			{ value: "grays", label: "Grays" },
			{ value: "greens", label: "Green" },
			{ value: "oranges", label: "Oranges" },
			{ value: "reds", label: "Reds" },
			{ value: "violets", label: "Violets" },
		],
		texture: [
			{ value: "pattern", label: "Pattern" },
			{ value: "loop", label: "Loop" },
			{ value: "texture", label: "Texture" },
			{ value: "twist", label: "Twist" },
		],
		material: [
			{ value: "nylon", label: "Nylon" },
			{ value: "polyester", label: "Polyester" },
			{ value: "ansoHighPerformance", label: "ANSO High-Performance" },
		],
		backing: [
			{ value: "classicBac", label: "ClassicBac" },
			{ value: "softBac", label: "SoftBac" },
			{ value: "lifeGuard", label: "LifeGuard" },
		],
	},
	vinyls: {
		color: [
			{ value: "beige-tan", label: "Beige/Tan" },
			{ value: "black", label: "Black" },
			{ value: "blue", label: "Blue" },
			{ value: "brown", label: "Brown" },
			{ value: "gold", label: "Gold" },
			{ value: "grey", label: "Grey" },
			{ value: "natural", label: "Natural" },
			{ value: "oranges", label: "Orange" },
			{ value: "red", label: "Red" },
			{ value: "rust", label: "Rust" },
			{ value: "taupe", label: "Taupe" },
			{ value: "white", label: "White" },
		],
		Installation_Method: [
			{ value: "float", label: "Float/Glueless" },
			{ value: "glue", label: "Direct Glue" },
		],
	},
	hardwoods: {
		color: [
			{ value: "beige", label: "Beige" },
			{ value: "beige-tan", label: "Beige/Tan" },
			{ value: "black", label: "Black" },
			{ value: "brown", label: "Brown" },
			{ value: "gold", label: "Gold" },
			{ value: "green", label: "Green" },
			{ value: "grey", label: "Grey" },
			{ value: "natural", label: "Natural" },
			{ value: "natural-beige", label: "Natural/Beige" },
			{ value: "oranges", label: "Orange" },
			{ value: "red", label: "Red" },
			{ value: "white", label: "White" },
		],
		collection: [
			{ value: "repel", label: "Repel" },
			{ value: "epic-plus", label: "Epic Plus" },
			{ value: "gallery", label: "The Gallery" },
			{ value: "floorte", label: "Floorte" },
		],
		texture: [
			{ value: "smooth", label: "Smooth" },
			{ value: "reclaimed-distressed", label: "Reclaimed/Distressed" },
			{ value: "scraped", label: "Scraped" },
			{ value: "wire-brushed", label: "Wire Brushed" },
		],
		Installation_Method: [
			{ value: "floating", label: "Floating" },
			{ value: "glue", label: "Glue" },
			{ value: "nail", label: "Nail" },
		],
	},
	doors: {
		style: [
			{ value: "french", label: "French" },
			{ value: "front-entry", label: "Front Entry Door" },
			{ value: "shaker", label: "Shaker" },
			{ value: "Colonial", label: "Colonial" },
		],
		color: [
			{ value: "paint-ready", label: "Paint Ready" },
			{ value: "blacks", label: "Blacks" },
			{ value: "unfinished", label: "Unfinished" },
			{ value: "nickel-tones", label: "Nickel Tones" },
			{ value: "silver-tones", label: "Silver Tones" },
			{ value: "stainless-steel", label: "Stainless Steel" },
			{ value: "whites", label: "Whites" },
			{ value: "browns", label: "Browns" },
			{ value: "light-wood-finishes", label: "Light Wood Finishes" },
		],
		brand: [
			{ value: "trimlite", label: "Trimlite" },
			{ value: "pinkys-iron-doors", label: "Pinkys Iron Doors" },
			{ value: "frameport", label: "Frameport" },
			{ value: "schlage", label: "Schlage" },
			{ value: "johnson-hardware", label: "Johnson Hardware" },
			{ value: "stile-doors", label: "Stile Doors" },
			{ value: "eclisse", label: "Eclisse" },
			{ value: "cavity-sliders", label: "Cavity Sliders" },
			{ value: "signature-hardware", label: "Signature Hardware" },
			{ value: "miseno", label: "Miseno" },
			{ value: "best-access", label: "Best Access" },
			{ value: "national-hardware", label: "National Hardware" },
		],
	},
	countertops: {
		color: [
			{ value: "beige", label: "Beige" },
			{ value: "black", label: "Black" },
			{ value: "blue", label: "Blue" },
			{ value: "brown", label: "Brown" },
			{ value: "gold", label: "Gold" },
			{ value: "gray", label: "Gray" },
			{ value: "green", label: "Greens" },
			{ value: "multicolor", label: "MultiColor" },
			{ value: "peach", label: "Peach" },
			{ value: "red", label: "red" },
			{ value: "white", label: "white" },
			{ value: "yellow", label: "Yellow" },
		],
		material: [
			{ value: "granite", label: "Granite" },
			{ value: "marble", label: "Marble" },
			{ value: "quartz", label: "Quartz" },
		],
		pattern: [
			{ value: "industrial", label: "Industrial" },
			{ value: "solid", label: "Solid" },
			{ value: "speckled", label: "Speckled" },
		],
		brand: [
			{ value: "arizona", label: "Arizona" },
			{ value: "caesarstone", label: "Caesarstone" },
			{ value: "lx-hausys", label: "LX Hausys" },
		],
	},
	laminates: {
		color: [
			{ value: "red", label: "red" },
			{ value: "white", label: "white" },
			{ value: "gray", label: "Gray" },
			{ value: "blonde", label: "Blonde" },
			{ value: "brown", label: "Brown" },
		],
		pattern: [
			{ value: "chervon", label: "Chervon" },
			{ value: "herringbone", label: "Herringbone" },
			{ value: "ornamental", label: "Ornamental" },
			{ value: "parquet", label: "Parquet" },
		],
		brand: [
			{ value: "dream-home", label: "Dream Home" },
			{ value: "aqualseal", label: "AquaSeal" },
			{ value: "major-brand", label: "Major Brand" },
		],
	},
	vanities: {
		brand: [
			{ value: "signature-hardware", label: "Signature Hardware" },
			{ value: "miseno", label: "Miseno" },
			{ value: "james-martin-vanities", label: "James Martin Vanities" },
			{ value: "wyndhamp-collection", label: "Wyndham Collection" },
			{ value: "dxv", label: "DXV" },
			{ value: "ariel", label: "Ariel" },
			{ value: "fresca", label: "Fresca" },
			{ value: "elegant-lighting", label: "Elegant Lighting" },
			{ value: "transolid", label: "Transolid" },
			{ value: "avanity", label: "Avanity" },
			{ value: "ws-bath-collections", label: "Ws Bath Collections" },
			{ value: "nameeks", label: "Nameeks" },
			{ value: "design-house", label: "Design House" },
			{ value: "swiss-madison", label: "Swiss Madison" },
			{ value: "kingston-brass", label: "Kingston Brass" },
			{ value: "kohler", label: "Kohler" },
			{ value: "altair", label: "Altair" },
			{ value: "ico-bath", label: "Ico Bath" },
			{ value: "duravit", label: "Duravit" },
			{ value: "jeffery-alexander", label: "Jeffery Alexander" },
			{ value: "craft-+-mAIN", label: "CRAFT + MAIN" },
			{ value: "robern", label: "Robern" },
			{ value: "linkasink", label: "Linkasink" },
			{ value: "native-trails", label: "Native Trails" },
			{ value: "sagehill-designs", label: "Sagehill Designs" },
			{ value: "sunny-wood", label: "Sunny Wood" },
			{ value: "ove-decors", label: "Ove Decors" },
			{ value: "msi", label: "MSI" },
			{ value: "strasser", label: "Strasser" },
			{ value: "cutler-kitchen", label: "Cutler Kitchen" },
			{ value: "american-standard", label: "American Standard" },
			{ value: "dreamline", label: "Dreamline" },
			{ value: "hanover", label: "Hanover" },
			{ value: "maplevilles-cabinetry", label: "Maplevilles Cabinetry" },
			{ value: "ryvyr", label: "Ryvyr" },
			{ value: "whitehaus", label: "Whitehaus" },
			{ value: "bellevue", label: "Bellevue" },
			{ value: "decoteak", label: "DecoTeak" },
		],
		style: [
			{ value: "single", label: "Single" },
			{ value: "double", label: "Double" },
			{
				value: "sinks-with-consoles-stands",
				label: "Sinks With Consoles Stands",
			},
			{ value: "console-stands", label: "Console Stands" },
		],
		color: [
			{ value: "whites", label: "Whites" },
			{ value: "geys", label: "Grays" },
			{ value: "blues", label: "Blues" },
			{ value: "blacks", label: "Blacks" },
			{ value: "light-wood-finishes", label: "Light Wood Finishes" },
			{ value: "dark-wood-finishes", label: "Dark Wood Finishes" },
			{ value: "medium-wood-finishes", label: "Medium Wood Finishes" },
			{ value: "browns", label: "Browns" },
			{ value: "green", label: "Greens" },
			{ value: "grays", label: "Grays" },
			{ value: "chromes", label: "Chromes" },
			{ value: "nickel-tones", label: "Nickel Tones" },
			{ value: "brass-tones", label: "Brass Tones" },
			{ value: "bronze-tones", label: "Bronze Tones" },
			{ value: "silver-tones", label: "Silver Tones" },
			{ value: "gold-tones", label: "Gold Tones" },
			{ value: "pinks", label: "Pinks" },
			{ value: "reds", label: "Reds" },
			{ value: "neutrals", label: "Neutrals" },
			{ value: "multi-colored", label: "Multi Colored" },
			{ value: "purples", label: "Purples" },
			{ value: "stainless-steel", label: "Stainless Steel" },
			{ value: "pewters", label: "Pewters" },
			{ value: "oranges", label: "Oranges" },
			{ value: "copper-tones", label: "Copper Tones" },
			{ value: "unfinished", label: "Unfinished" },
			{ value: "creams", label: "Creams" },
		],
		Faucet_Finish: [
			{ value: "chrome", label: "Chrome" },
			{ value: "brushed-nickel", label: "Brushed Nickel" },
		],
		Sink_Material: [
			{ value: "ceramic", label: "Ceramic" },
			{ value: "porcelain", label: "Porcelain" },
			{ value: "vitreous-china", label: "Vitreous" },
			{ value: "acrylic", label: "Acrylic" },
			{ value: "cultured-marble", label: "Cultured Marble" },
			{ value: "solid-surface", label: "Solid Surface" },
			{ value: "solid-surface", label: "Solid Surface" },
			{ value: "marble", label: "Marble" },
			{ value: "stone-composite", label: "Stone Composite" },
			{ value: "glass", label: "Glass" },
			{ value: "resin", label: "Resin" },
			{ value: "natural-stone", label: "Natural Stone" },
			{ value: "concrete", label: "Concrete" },
			{ value: "firecly", label: "Firecly" },
			{ value: "stainless-still", label: "Stainless Still" },
			{ value: "cast-iron", label: "Cast Iron" },
			{ value: "granite", label: "Granite" },
			{ value: "copper", label: "Copper" },
			{ value: "engineered-stone", label: "Engineered Stone" },
			{ value: "tempered-glass", label: "Tempered Glass" },
			{ value: "brass", label: "Brass" },
			{ value: "composite", label: "Composite" },
			{ value: "steel", label: "Steel" },
		],
	},
	faucets: {
		brand: [
			{ value: "kingston-brass", label: "Kingston Brass" },
			{ value: "graff", label: "Graff" },
			{ value: "california", label: "California" },
			{ value: "delta", label: "Delta" },
			{ value: "chicago", label: "Chicago" },
			{ value: "moen", label: "Moen" },
			{ value: "t-and-s-brass", label: "T and S Brass" },
			{ value: "kohler", label: "Kohler" },
			{ value: "signature-hardware", label: "Signature Hardware" },
			{ value: "rohl", label: "Rohl" },
			{ value: "zurn", label: "Zurn" },
			{ value: "ements-of-design", label: "Ements Of Design" },
			{ value: "brizo", label: "Brizo" },
			{ value: "newport-brass", label: "Newport Brass" },
			{ value: "toto", label: "ToTo" },
			{ value: "riobel", label: "Riobel" },
			{ value: "hansgrohe", label: "Hansgrohe" },
			{ value: "pfister", label: "Pfister" },
			{ value: "jaclo", label: "Jaclo" },
			{ value: "nameeks", label: "Nameeks" },
			{ value: "american-standard", label: "American Standard" },
			{ value: "proflo", label: "Proflo" },
			{ value: "speakman", label: "Speakman" },
			{ value: "elkay", label: "Elkay" },
			{ value: "axor", label: "Axor" },
			{ value: "symmons", label: "Symmons" },
			{ value: "grohe", label: "Grohe" },
			{ value: "perrin-and-rowe", label: "Perrin And Rowe" },
			{ value: "gerber", label: "Gerber" },
			{ value: "central-brass", label: "Central Brass" },
			{ value: "pioneer-faucets", label: "Pioneer Faucets" },
			{ value: "kallista", label: "Kallista" },
			{ value: "peerless", label: "Peerless" },
			{ value: "brondell", label: "Brondell" },
			{ value: "build-essentials", label: "Build Essentials" },
			{ value: "asi", label: "ASI" },
			{ value: "biobidet", label: "Biobidet" },
			{ value: "hai", label: "Hai" },
			{ value: "meditub", label: "MediTub" },
			{ value: "ove-decors", label: "Ove Decors" },
			{ value: "bobrick", label: "bobrick" },
			{ value: "Everpure", label: "everpure" },
			{ value: "halsey-taylor", label: "Halsey Taylor" },
			{ value: "lynx grills", label: "Lynx Grills" },
			{ value: "premier-copper", label: "Premier Copper" },
			{ value: "sedona-by-lynx", label: "Sedona By Lynx" },
			{ value: "wyndhamp-collection", label: "Wyndham Collection" },
		],
		style: [
			{ value: "double-handle", label: "Double Handle" },
			{ value: "single handle", label: "Single Handle" },
			{ value: "pressure-balanced", label: "Pressure-Balanced" },
			{ value: "single-function", label: "Single Function" },
			{ value: "multi-function", label: "Multi Function" },
		],
		color: [
			{ value: "chromes", label: "Chromes" },
			{ value: "nickel-tones", label: "Nickel Tones" },
			{ value: "blacks", label: "Blacks" },
			{ value: "bronze-tones", label: "Bronze-Tones" },
			{ value: "gold-tones", label: "Dark Wood Finishes" },
			{ value: "brass-tones", label: "Medium Wood Finishes" },
			{ value: "stainless-steel", label: "Stainless Steel" },
			{ value: "whites", label: "Whites" },
			{ value: "copper-tones", label: "Copper Tones" },
			{ value: "neutrals", label: "Neutrals" },
			{ value: "greys", label: "Greys" },
			{ value: "silver-tones", label: "Silver Tones" },
			{ value: "pewters", label: "Pewters" },
			{ value: "blues", label: "Blues" },
			{ value: "steel-tones", label: "Steel Tones" },
			{ value: "reds", label: "Reds" },
			{ value: "browns", label: "Browns" },
			{ value: "multi-colored", label: "Multi Colored" },
			{ value: "light-wood-finishes", label: "Light-Wood-Finishes" },
			{ value: "pinks", label: "Pinks" },
			{ value: "yellows", label: "Yellows" },
			{ value: "greens", label: "Greens" },
			{ value: "grays", label: "Grays" },
			{ value: "oranges", label: "Oranges" },
			{ value: "purples", label: "Purples" },
			{ value: "creams", label: "Creams" },
			{ value: "dark-wood-finishes", label: "Dark Wood Finishes" },
		],
	},
	sinks: {
		brand: [
			{ value: "elkay", label: "Elkay" },
			{ value: "ws-bath-collections", label: "Ws Bath Collections" },
			{ value: "nameeks", label: "Nameeks" },
			{ value: "kohler", label: "Kohler" },
			{ value: "vigo", label: "Vigo" },
			{ value: "kingston-brass", label: "Kingston Brass" },
			{ value: "ruvati", label: "Ruvati" },
			{ value: "kraus", label: "kraus" },
			{ value: "signature-hardware", label: "Signature Hardware" },
			{ value: "msi", label: "MSI" },
		],
		types: [
			{ value: "type1", label: "Type1" },
			{ value: "msi", label: "MSI" },
		],
		color: [
			{ value: "whites", label: "Whites" },
			{ value: "stainless-steel", label: "Stainless Steel" },
			{ value: "blacks", label: "Blacks" },
			{ value: "greys", label: "Greys" },
			{ value: "neutrals", label: "Neutrals" },
			{ value: "nickel-tones", label: "Nickel Tones" },
			{ value: "browns", label: "Browns" },
			{ value: "chromes", label: "Chromes" },
			{ value: "bronze-tones", label: "Bronze-Tones" },
			{ value: "copper-tones", label: "Copper Tones" },
			{ value: "gold-tones", label: "Dark Wood Finishes" },
			{ value: "brass-tones", label: "Medium Wood Finishes" },
			{ value: "silver-tones", label: "Silver Tones" },
			{ value: "blues", label: "Blues" },
			{ value: "steel-tones", label: "Steel Tones" },
			{ value: "greens", label: "Greens" },
			{ value: "clear", label: "Clear" },
			{ value: "reds", label: "Reds" },
			{ value: "grays", label: "Grays" },
			{ value: "yellows", label: "Yellows" },
			{ value: "pinks", label: "Pinks" },
			{ value: "light-wood-finishes", label: "Light-Wood-Finishes" },
			{ value: "multi-colored", label: "Multi Colored" },
			{ value: "oranges", label: "Oranges" },
			{ value: "creams", label: "Creams" },
			{ value: "dark-wood-finishes", label: "Dark Wood Finishes" },
			{ value: "purples", label: "Purples" },
			{ value: "medium-wood-finishes", label: "Medium Wood Finishes" },
			{ value: "pewters", label: "Pewters" },
		],
		Faucet_Finish: [
			{ value: "chrome", label: "Chrome" },
			{ value: "matte-black", label: "Matte Black" },
			{ value: "brushed-nickel", label: "Brushed Nickel" },
		],
		shape: [
			{ value: "rectangular", label: "Rectangle" },
			{ value: "round", label: "Round" },
			{ value: "oval", label: "Oval" },
			{ value: "square", label: "Square" },
		],
	},
};
